### ISSUE TITLE
Annotated Tonsil B cell Seurat Object?

### ISSUE THREAD

**Issue by david-priest** [massonix/HCATonsilData#30]
I was able to locate the top level Seurat object, that has the cell type annotations from Figure 1
https://zenodo.org/records/8373756

But I cannot locate the other Seurat objects, and in particular I'm interested in the one from Figure 4.

Also, I'm able to run Azimuth locally on Tonsil V2, but again that UMAP looks different from the paper.
https://app.azimuth.hubmapconsortium.org/app/human-tonsil-v2

**Comment by massonix** [comment]
Hi @purisuto,

It is totally expectected that the UMAPs will be different, because the data was reprocessed by the Azimuth team before uploading it to the server. We worked together to ensure that the clusters are conserved and everything makes sense.

You should also be able to convert the SingleCellExperiment objects to Seurat using as.Seurat. In any case, you can download the Seurat objects from Zenodo following this vignette

https://github.com/massonix/HCATonsilData/blob/devel/inst/scripts/make-data-tonsil-atlas-rna-v2.Rmd

Ramon

**Comment by david-priest** [comment]
Got it. Much appreciated.

Since I'm also using UCell for gene scoring, how do you recommend generating gene lists as per Table S4 of the previous work (https://www.science.org/doi/full/10.1126/sciimmunol.abe6291#supplementary-materials)?  I'm currently using `FindAllMarkers()`

**Comment by massonix** [comment]
FindAllMarkers is what we used as well!

**Comment by david-priest** [comment]
Ok thank you very much for the advice and the great resource.
